# Generated by Django 3.0.7 on 2020-06-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsaverapi', '0004_job_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
