# Generated by Django 3.0.7 on 2020-06-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsaverapi', '0006_auto_20200622_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_status',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job_status',
            old_name='status_id',
            new_name='status',
        ),
    ]
