# Generated by Django 3.0.7 on 2020-06-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsaverapi', '0007_auto_20200623_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_status',
            old_name='job',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='job_status',
            old_name='status',
            new_name='status_id',
        ),
    ]
