# Generated by Django 3.0.7 on 2020-06-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsaverapi', '0008_auto_20200623_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_status',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job_status',
            old_name='status_id',
            new_name='status',
        ),
    ]
